<?php


$title = 'Edit Image Style';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<div>
    <div style="float:left">
        <h3>Original</h3>
        <image src="/files/images/image.jpg" width="300">
    </div>
    <div style="float:right;">
        <h3>Processed</h3>
        <?php echo $this->zf2Image('/files/images/image.jpg', $style_name, true); ?>
    </div>
</div>




<?php

//TODO : Delete it out of here. Make view helper.
function _display_image_options($option, $value){
    if (is_array($value)) {
        echo $option . ': (';
        foreach ($value as $suboption => $subvalue) {
            _display_image_options($suboption, $subvalue);
        }
        echo ') ';
    } else {
        echo $option . ': ' . $value . '; ';
    }
}

?>

<table class="table">
    <thead>
        <tr>
            <th>Operation</th>
            <th>Options</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>

        <?php foreach ($operations as $row) : ?>
            <tr>
                <td><?php echo $row['operation']; ?></td>
                <td>
                    <?php
                    if(isset($row['options']) && is_array($row['options'])){
                        foreach($row['options'] as $option => $value){
                            _display_image_options($option, $value);
                        }
                    }
                    ?>
                </td>
                <td></td>
                <td></td>

            </tr>
        <?php endforeach; ?>
    </tbody>
</table>










<?php
$form = $this->form;
$form->setAttribute('action', $this->url('adminzf2image', array('action' => 'edit', 'style_name' => $style_name)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('operation'));
echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();

?>